{% set version = "0.6.0" %}
{% set name = "bluesky-kafka" %}
{% set sha256 = "beab97dead2597eb475124d024b2c9a81fc7ba035eb87d7c08d8934c707cbe4e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - bluesky
    - python-confluent-kafka

test:
  imports:
    - bluesky_kafka

about:
  home: https://github.com/bluesky/bluesky-kafka
  license: BSD-3-Clause
  license_file: LICENSE
  summary: The bluesky-kafka module
  dev_url: https://github.com/bluesky/bluesky-kafka
