{% set version = "0.2.0" %}
{% set name = "bluesky-kafka" %}
{% set sha256 = "1e16997240c2ca9ca7feea79810a63ff70afa35a177c777818ee65fdd2aebd9b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - bluesky
    - python-confluent-kafka

test:
  imports:
    - bluesky_kafka

about:
  home: https://github.com/bluesky/bluesky-kafka
  license: BSD-3-Clause
  license_file: LICENSE
  summary: The bluesky-kafka module
